name: Build
on: [push]
jobs:
  python-formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 .
  
  unit-test:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Run pytest
      run: pytest src/test_app.py

  deploy-to-impaas:
    needs: [python-formatting, unit-test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ImPaaS-Deploy
      uses: /impaas/impaas-deploy@v3
      with:
        app-name: sco115-sse-lab2
        deployment-token: ${{ secrets.IMPAAS_DEPLOY_TOKEN }}
        method: PLATFORM

  
